version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "13:00"
  open-pull-requests-limit: 10
  versioning-strategy: increase-if-necessary
  ignore:
  - dependency-name: puppeteer
    versions:
    - 8.0.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.1
